$("#modedark").click(function(){
$("body").toggleClass("Night")}),$("body").toggleClass(localStorage.toggled),$("#modedark").click(function(){
"Night"!=localStorage.toggled?($("body").toggleClass("Night",!0),localStorage.toggled="Night"):($("body").toggleClass("Night",!1),localStorage.toggled="")
});
if (localStorage.toggled == "Night") {$(".post-body font").removeAttr("color"); $(".post-body font").replaceWith(function () { return "<b>" + $(this).text() + "</b>"; });}else{};
function newsPosts(a){var e=a.feed.entry,title,link,cat,date,content="",ct=document.getElementById("news-posts");for(var i=0;i<e.length;i++){for(var j=0;j<e[i].category.length;j++){if(e[i].category[j].term=='Tank'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj52-0G12AK8h8nZt-rmt5S6Dyfc701QuzIbR6rV7CyuymqcJIL64HvvTktp4dtKJS3To1AAldvW3ZAx80P_OK2QpUsfTo5hwptoUFmDPgPtLL8YjCB5o-xz0VZ5LlJQHSvuKdY-OPLE6M2zamQKZh1LYIVrRGKOCv5YO0FhllWqUFDWRAQVNN0IYkxew/w100-rw/Tank_Icon.png'}
if(e[i].category[j].term=='Fighter'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEita1UgjfrrqTEhZfc2iofXlkbnIJlXhXntmA54Q2Di-bNtJ5hC04koNcKRtDR49vBMoLoTCfGp5hGrx83GgKZNaLbvUruWlcECrkDRVL5vinwW6iyncDgg-9wLzSK1MkLqsf2CyU6_tDPopG7dJEsjZV2kF7wLb1mSy0kPMLvtHA9_UoD3QTLzHdF8hA/w100-rw/Fighter_Icon.png'}
if(e[i].category[j].term=='Assassin'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhzTZeijpq7CK7XwJjFyry6A6VFYq3IIc320hqI3ITep3rXt6fiBOAh6z1MpFn5PkFWnKm1n0QU0aZO-zoRA2RWzsvw9pOxv3mwVrFnjAkHLdRhFAoOYmTKYy7Z57KzvIn026ZBXUM-hWJiOsC3Rd4nisdhqn8hWrn8weATa4BGmcztEaWxZeoKBkDDZA/w100-rw/Assassin_Icon.png'}
if(e[i].category[j].term=='Marksman'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhEuj7n8wjJ-F28UIS7SrunWhmtlpMNZ9MuWfluGfilLCHWTJJk9vxBmiItS43t6IYU6w6oCtBqYFpxK4V_rygqM9GehkMx3jyDdC4VTaZJVmqXaOi9t7HbtFPKWUn6FjwxR-ZXaoI4K2mvBeiqrEe4RCZUv9EaJ_Mk_LhU4dqWzpxsoyY2-09OZxY8tA/w100-rw/Marksman_Icon.png'}
if(e[i].category[j].term=='Mage'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhmrYiNLhYQUhCzeRNEstC4b1vJz4oSVr_nuhb4x93fCnElvDnP6yRP7r8j-3caud3hu89FTJ9GP_Y_us3Qif8_9-EuCx-1ZY1u3megS8COKu_u1ZC7ZLPy9vc7oIG-YJ1QQTj5ms26m17N2sYmXFtIEAbaLvciw5t3D2nNchIYjLispMEv1JT52uWtpg/w100-rw/Mage_Icon.png'}
if(e[i].category[j].term=='Support'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgi8cvcDLIbZek5yjGSfI03YsihNqm9GXDOFSRY3gh6wKXe5wsRZ6aeylZ61JU9V1FWgML6-qgxh1mQdBUvWCaXPoxT1E415o2OrusSrVx4czjKrWlaxfadm94b9T6IgoFysjHXXecfX_Rf4jK2VmA3NvToaG3ohtHkuZ-3Qmowo4Rz8z6WfE-CCY4_bA/w100-rw/Support_Icon.png'}}; var title=e[i].title.$t; for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var date=e[i].published.$t;content+='<a href="'+link+'" title="'+title+'" rel="nofollow" style="color:#ffb3b3"><span class="notranslate" style="margin-right:15px;border:0.5px solid #fcfcfc;border-radius:5px;padding:3px"><span class="caty" style="display:inline-block;background-image:url(' + cat + ');background-repeat:no-repeat; background-position:center;background-size:contain;width:15px;height:15px;background-color:transparent;border-radius:10px;margin:auto 0 -2.5px"></span> <b>'+title+' (' + date.substring(0, 4) + ')</b></span></a>'}ct.innerHTML=content}; var news_post=document.createElement('script');news_post.src='/feeds/posts/summary?redirect=false&alt=json-in-script&orderby=updated&max-results=15&callback=newsPosts';document.getElementsByTagName('head')[0].appendChild(news_post);
function randomPosts(a){var e=shuffleArray(a.feed.entry),title,link,cat,date,img,content="",ct=document.getElementById("random-posts");for(var i=0;i<12;i++){for(var j=0;j<e[i].category.length;j++){if(e[i].category[j].term=='Tank'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj52-0G12AK8h8nZt-rmt5S6Dyfc701QuzIbR6rV7CyuymqcJIL64HvvTktp4dtKJS3To1AAldvW3ZAx80P_OK2QpUsfTo5hwptoUFmDPgPtLL8YjCB5o-xz0VZ5LlJQHSvuKdY-OPLE6M2zamQKZh1LYIVrRGKOCv5YO0FhllWqUFDWRAQVNN0IYkxew/w100-rw/Tank_Icon.png'}
if(e[i].category[j].term=='Fighter'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEita1UgjfrrqTEhZfc2iofXlkbnIJlXhXntmA54Q2Di-bNtJ5hC04koNcKRtDR49vBMoLoTCfGp5hGrx83GgKZNaLbvUruWlcECrkDRVL5vinwW6iyncDgg-9wLzSK1MkLqsf2CyU6_tDPopG7dJEsjZV2kF7wLb1mSy0kPMLvtHA9_UoD3QTLzHdF8hA/w100-rw/Fighter_Icon.png'}
if(e[i].category[j].term=='Assassin'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhzTZeijpq7CK7XwJjFyry6A6VFYq3IIc320hqI3ITep3rXt6fiBOAh6z1MpFn5PkFWnKm1n0QU0aZO-zoRA2RWzsvw9pOxv3mwVrFnjAkHLdRhFAoOYmTKYy7Z57KzvIn026ZBXUM-hWJiOsC3Rd4nisdhqn8hWrn8weATa4BGmcztEaWxZeoKBkDDZA/w100-rw/Assassin_Icon.png'}
if(e[i].category[j].term=='Marksman'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhEuj7n8wjJ-F28UIS7SrunWhmtlpMNZ9MuWfluGfilLCHWTJJk9vxBmiItS43t6IYU6w6oCtBqYFpxK4V_rygqM9GehkMx3jyDdC4VTaZJVmqXaOi9t7HbtFPKWUn6FjwxR-ZXaoI4K2mvBeiqrEe4RCZUv9EaJ_Mk_LhU4dqWzpxsoyY2-09OZxY8tA/w100-rw/Marksman_Icon.png'}
if(e[i].category[j].term=='Mage'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhmrYiNLhYQUhCzeRNEstC4b1vJz4oSVr_nuhb4x93fCnElvDnP6yRP7r8j-3caud3hu89FTJ9GP_Y_us3Qif8_9-EuCx-1ZY1u3megS8COKu_u1ZC7ZLPy9vc7oIG-YJ1QQTj5ms26m17N2sYmXFtIEAbaLvciw5t3D2nNchIYjLispMEv1JT52uWtpg/w100-rw/Mage_Icon.png'}
if(e[i].category[j].term=='Support'){var cat='https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgi8cvcDLIbZek5yjGSfI03YsihNqm9GXDOFSRY3gh6wKXe5wsRZ6aeylZ61JU9V1FWgML6-qgxh1mQdBUvWCaXPoxT1E415o2OrusSrVx4czjKrWlaxfadm94b9T6IgoFysjHXXecfX_Rf4jK2VmA3NvToaG3ohtHkuZ-3Qmowo4Rz8z6WfE-CCY4_bA/w100-rw/Support_Icon.png'}}; var title=e[i].title.$t; for (var l=0;l<e[i].link.length;l++){if (e[i].link[l].rel=="alternate"){var link= e[i].link[l].href;break}}; var date=e[i].published.$t;try {img = e[i].media$thumbnail.url} catch (h) {s = e[i].content.$t;a = s.indexOf('<img');b = s.indexOf('src="', a);c = s.indexOf('"', b + 5);d = s.substr(b + 5, c - b - 5);if (a != -1 && b != -1 && c != -1 && d != "") {img = d}}
content+='<div class="list"><a href="' + link + '" rel="nofollow"><div class="item-thumbnail" style="background-image: url(' + img + ')"><div class="post-date" style="position:absolute;top:0;right:0;padding:2px;font-size:50%;color:#ffffff;border-radius:15px">' + date.substring(0, 4) + '</div><div class="caty" style="display:block;position:absolute;bottom:5px;left:5px;background-image: url(' + cat + ');background-repeat: no-repeat; background-position: center;background-size:contain;width:14px;height:14px;background-color:rgba(0,0,0,.7);border-radius:2px"></div></div><div class="notranslate item-title">' + title + '</div></div>'}ct.innerHTML=content};
function shuffleArray(arr){var i=arr.length,j,temp;if(i===0)return false;while(--i){j=Math.floor(Math.random()*(i+1));temp=arr[i];arr[i]=arr[j];arr[j]=temp}return arr}var random_post=document.createElement('script');random_post.src='/feeds/posts/default?alt=json-in-script&orderby=published&max-results=999&callback=randomPosts';document.getElementsByTagName('head')[0].appendChild(random_post);
var lazyadsense=!1;window.addEventListener("scroll",function(){(0!=document.documentElement.scrollTop&&!1===lazyadsense||0!=document.body.scrollTop&&!1===lazyadsense)&&(!function(){var e=document.createElement("script");e.async="async",e.src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2746726314208711";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(e,a)}(),lazyadsense=!0)},!0); (adsbygoogle = window.adsbygoogle || []).push({google_ad_client: "ca-pub-2746726314208711",enable_page_level_ads: true}); var logourl=$(".logo-container a").attr('href');
$(".mysiteurl").html(logourl); var logoalt=$(".logo-container img.logo").attr('alt');
$(".mysitename").html(logoalt);
$(".developergame").html("Shanghai Moonton Technology Co. Ltd.");
function getCurrentYear(){var e=new Date;return e.getFullYear()}el=document.getElementById("current-year"),el.innerHTML=getCurrentYear();